[package]
name = "sword-ward"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.6"
png = "0.17.16"
thin-engine = { version = "0.5.0", features = ["text"] }
tobj = "4.0.3"

[profile.release]
opt-level = 3
lto = true
